services:
  frontend:
    container_name: front
    build: 
      context: '.'
      dockerfile: ./container/Dockerfile.frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/src/frontend
      - node_modules:/usr/src/frontend/node_modules # node_modules
    tty: true
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true

volumes:
  node_modules: